### PR TITLE
Fixes issue #35 - FITS CUNIT 'M/S' header.

### PR DESCRIPTION
**Pull request by razman786**
Fixes issue #35 - FITS CUNIT 'M/S' header.

`wcslib` needs 'M/S' to be lower case 'm/s' - a simple fix that updates the header.

### CODE REVIEW

**Review by Athanaseus — APPROVED** [review]
LGTM!

**Comment by razman786** [comment]
A refined version of this PR has already been added to PR #37 for the purposes of PR 130 (https://github.com/ratt-ru/tigger/pull/130).

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
The failure stems from usage of format strings:
```
[0m[91m2022-05-23 08:40:06	INFO	imager::createFTMachine() 	Performing interferometric gridding...
[0mlwimager normally ended
[91mTraceback (most recent call last):
  File "/usr/local/bin/tigger-convert", line 118, in <module>
    from Tigger import Coordinates
  File "/usr/local/lib/python2.7/dist-packages/Tigger/Coordinates.py", line 371
    raise RuntimeError(f"Error WCS header {e}")
                                             ^
SyntaxError: invalid syntax
[0m[91mE[0m[91m
======================================================================
[0m[91mERROR: batch_test.testMeqtreesBatchJob
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/src/pyxis-1.7.1/Pyxis/recipes/meqtrees-batch-test/batch_test.py", line 112, in testMeqtreesBatchJob
    run("""tigger-convert {0:s}/test-lsm.txt --rename --format "ra_d dec_d i q u v" --center 0.1deg,60.5deg -f""".format(PACKAGE_TEST_DIR));
  File "/src/pyxis-1.7.1/Pyxis/recipes/meqtrees-batch-test/batch_test.py", line 43, in run
    raise RuntimeError("failed with exit co
```

Recall that I added backport facilities for Python 2.7 to fix the previous Tigger. If you want to remove these go ahead.

**Comment by razman786** [comment]
@bennahugo - Ah yes I recall now (took a bit). Is anyone using `tigger-lsm` with Python 2.7? If not then may be the Travis test needs to be retired?

**Comment by bennahugo** [comment]
We just need to make sure that the current release only targets 3.0x for those who are still on an older Tigger so we don't break the dependency tree. Then we can retire the failing build.

**Comment by bennahugo** [comment]
Specifically this needs changing: https://github.com/ratt-ru/tigger-lsm/blob/master/setup.py#L32

**Pull request merged**
