### PR TITLE
Upgrade astLib for Python>=3.12.

### PR DESCRIPTION
**Pull request by JSKenyon**
This tiny PR should make tigger-lsm compatible with Python3.12.

### CODE REVIEW

**Comment by bennahugo** [comment]
ok to test

**Comment by JSKenyon** [comment]
Ok @bennahugo - the tests seem to be passing. Could you review when you have a moment?

**Comment by bennahugo** [comment]
Getting the following from the build system now:
```
Step 9/17 : RUN pip install ./tigger-lsm
 ---> Running in 87329fb79b14
Processing ./tigger-lsm
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting astlib<=0.11.10 (from astro-tigger-lsm==1.7.4)
  Downloading astLib-0.11.10.tar.gz (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 85.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting astro-kittens<2.0.0,>=1.4.6 (from astro-tigger-lsm==1.7.4)
  Downloading astro-kittens-1.4.6.tar.gz (37 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
[91m  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info
      writing /tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-uhh1f6cp/astro_kittens.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jy6mpn6w/astro-kittens_5e21b14822d34f0ba779965e6467f648/setup.py", line 7, in <module>
          setup(name='astro-kittens',
        File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 313, in run
          self.find_sources()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 321, in find_sources
          mm.run()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 549, in run
          self.prune_file_list()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/sdist.py", line 162, in prune_file_list
          super().prune_file_list()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```

**Comment by bennahugo** [comment]
Proposed fix is to downgrade setuptools to 70.x Perhaps we need to pin this as a requirement in the toml file per https://github.com/pypa/setuptools/issues/4483

**Comment by bennahugo** [comment]
Ok I can at least confirm it is an upstream regression in pypa/setuptools#4483 since the last PR to move the build system to poetry.

**Comment by bennahugo** [comment]
So ```pip -U setuptools wheel pip``` no longer works and pip does not specify the core dependencies on specific versions of setuptools correctly per pypa/setuptools#4483. The solution is to do ```pip -U setuptools[core] wheel pip``` which is a bit arcane bekludgery to get the build system installer to meet its own dependencies. Hopefully pypa will fix this at some point

**Pull request merged**
